using Development_Demand_Forecasting.Model;
using Google.GenAI;
using Google.GenAI.Types;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace Development_Demand_Forecasting
{

    public partial class MainWindow : Window
    {
        private readonly Development_Demand_Forecasting.Model.AppContext context;


        public MainWindow()
        {
            InitializeComponent();
            context = new Development_Demand_Forecasting.Model.AppContext();
            context.Database.EnsureCreated();

        }

        private void Border_MouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        {
            if (e.ClickCount == 2)
            {
                this.WindowState = this.WindowState == WindowState.Maximized ? WindowState.Normal : WindowState.Maximized;
            }
            else if (e.ChangedButton == MouseButton.Left)
            {
                if (this.WindowState == WindowState.Maximized)
                {
                    double percentHorizontal = e.GetPosition(this).X / this.ActualWidth;
                    double percentVertical = e.GetPosition(this).Y / this.ActualHeight;

                    this.WindowState = WindowState.Normal;

                    this.Left = e.GetPosition(null).X - (this.ActualWidth * percentHorizontal);
                    this.Top = e.GetPosition(null).Y - (this.ActualHeight * percentVertical);
                }

                this.DragMove();
            }
        }

        private void accountsDataGrid_RowEditEnding(object sender, DataGridRowEditEndingEventArgs e)
        {
            if (e.EditAction == DataGridEditAction.Commit)
            {
                Dispatcher.BeginInvoke(System.Windows.Threading.DispatcherPriority.Background, new Action(() =>
                {
                    try
                    {
                        context.ChangeTracker.DetectChanges();
                        if (context.ChangeTracker.HasChanges())
                        {
                            context.SaveChanges();
                        }
                    }
                    catch (Exception ex)
                    {
                        MessageBox.Show($"Error saving: {ex.Message}");
                    }
                }));
            }
        }

        private void accountsDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            var grid = sender as DataGrid;

            var actionColumn = grid.Columns.FirstOrDefault(c => c.Header.ToString() == "Actions");

            if (actionColumn != null)
            {
                actionColumn.DisplayIndex = grid.Columns.Count - 1;
            }
        }

        private void accountsDataGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            var propertyDescriptor = e.PropertyDescriptor as System.ComponentModel.PropertyDescriptor;
            if (propertyDescriptor == null) return;

            var entityType = context.Model.FindEntityType(propertyDescriptor.ComponentType);

            if (entityType != null)
            {
                var primaryKey = entityType.FindPrimaryKey();

                if (primaryKey != null && primaryKey.Properties.Any(p => p.Name == e.PropertyName))
                {
                    if (e.PropertyType == typeof(int))
                    {
                        e.Column.Visibility = Visibility.Collapsed;
                    }
                    else
                    {
                        e.Column.IsReadOnly = true;
                    }

                }
            }

            if (e.PropertyType.IsClass && e.PropertyType != typeof(string))
            {
                e.Cancel = true;
            }

            if (e.PropertyType == typeof(DateTime))
            {
                (e.Column as DataGridTextColumn).Binding.StringFormat = "yyyy-MM-dd";
            }
        }

        private void Products_Checked(object sender, RoutedEventArgs e)
        {
            context.Products.Load();
            accountsDataGrid.ItemsSource = context.Products.Local.ToObservableCollection();
        }

        private void Suppliers_Checked(object sender, RoutedEventArgs e)
        {
            context.Suppliers.Load();
            accountsDataGrid.ItemsSource = context.Suppliers.Local.ToObservableCollection();
        }

        private void Warehouses_Checked(object sender, RoutedEventArgs e)
        {
            context.Warehouses.Load();
            accountsDataGrid.ItemsSource = context.Warehouses.Local.ToObservableCollection();
        }

        private void Inventory_Checked(object sender, RoutedEventArgs e)
        {
            context.Inventory.Load();
            accountsDataGrid.ItemsSource = context.Inventory.Local.ToObservableCollection();
        }

        private void Sales_Checked(object sender, RoutedEventArgs e)
        {
            context.SalesHistory.Load();
            accountsDataGrid.ItemsSource = context.SalesHistory.Local.ToObservableCollection();
        }

        private void Minus_Click(object sender, RoutedEventArgs e)
        {
            this.WindowState = WindowState.Minimized;
        }

        private void Maximize_Click(object sender, RoutedEventArgs e)
        {
            if (this.WindowState == WindowState.Normal)
            {
                this.WindowState = WindowState.Maximized;
            }
            else
            {
                this.WindowState = WindowState.Normal;
            }
        }

        private void Close_Click(object sender, RoutedEventArgs e)
        {
            Application.Current.Shutdown();
        }

        private bool isPanelOpen = true;

        private void Menu_Click(object sender, RoutedEventArgs e)
        {
            double from = isPanelOpen ? 0 : -SidePanel.ActualWidth;
            double to = isPanelOpen ? -SidePanel.ActualWidth : 0;

            // Animate SidePanel sliding
            var animation = new DoubleAnimation
            {
                From = from,
                To = to,
                Duration = TimeSpan.FromMilliseconds(300),
                EasingFunction = new QuadraticEase
                {
                    EasingMode = EasingMode.EaseInOut
                }
            };
            SidePanelTransform.BeginAnimation(TranslateTransform.XProperty, animation);

            // Animate MainBoard expanding
            Storyboard mainBoardStoryboard = isPanelOpen
                ? (Storyboard)FindResource("ExpandMainBoardStoryboard")
                : (Storyboard)FindResource("CollapseMainBoardStoryboard");

            mainBoardStoryboard.Begin();

            isPanelOpen = !isPanelOpen;
        }

        private async void Forcast_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                if (sender is Button btn)
                {
                    if (btn.Content is StackPanel sp)
                    {
                        foreach (var child in sp.Children)
                        {
                            if (child is TextBlock tb)
                            {
                                tb.Text = "In Progress";
                                break;
                            }
                        }
                    }
                }

                var client = new Client(apiKey: "AIzaSyDpz43xDCKmE2Q3k7KQGaMy8r2k7UsuiB4");

                var salesData = context.SalesHistory
                    .ToList();

                var products = context.Products
                    .ToList();

                var inventory = context.Inventory
                    .ToList();

                var productDataList = salesData
                    .GroupBy(s => s.ProductId)
                    .Select(g =>
                    {
                        var productName = products.FirstOrDefault(p => p.ProductId == g.Key)?.Name ?? "Unknown";

                        var monthlySales = g
                            .GroupBy(s => new DateTime(s.Date.Year, s.Date.Month, 1))
                            .Select(mg => mg.Sum(x => x.Quantity))
                            .ToList();

                        var currentStock = inventory.FirstOrDefault(i => i.ProductId == g.Key)?.QuantityOnHand ?? 0;

                        return $"Data for Product {g.Key} ({productName}):\nMonthly sales: [{string.Join(",", monthlySales)}]\nCurrent stock: {currentStock}";
                    })
                    .ToList();

                string dataString = string.Join("\n\n", productDataList);

                string prompt = $@"
            Forecast next month's demand for each product below.
            Return ONLY valid JSON for each product.

            {dataString}

            Output format per product:
              ProductId: number,
              ProductName: text,
              forecast: number,
              recommended_order: number";

                var response = await client.Models.GenerateContentAsync(
                    model: "gemini-3-flash-preview",
                    contents: prompt
                );

                string result = response.Candidates[0].Content.Parts[0].Text;

                MessageBox.Show(result, "Forecast Result", MessageBoxButton.OK, MessageBoxImage.Information);

                if (sender is Button btnReset)
                {
                    if (btnReset.Content is StackPanel spReset)
                    {
                        foreach (var child in spReset.Children)
                        {
                            if (child is TextBlock tb)
                            {
                                tb.Text = "Forcast";
                                break;
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Error: {ex.Message}", "Forecast Error", MessageBoxButton.OK, MessageBoxImage.Error);

                if (sender is Button btnReset)
                {
                    if (btnReset.Content is StackPanel spReset)
                    {
                        foreach (var child in spReset.Children)
                        {
                            if (child is TextBlock tb)
                            {
                                tb.Text = "Forcast";
                                break;
                            }
                        }
                    }
                }
            }
        }
        private async void DeleteRow_Click(object sender, RoutedEventArgs e)
        {
            if (sender is not Button button)
                return;

            var item = button.DataContext;

            // Не удаляем пустую строку добавления
            if (item == null ||
                item == System.Windows.Data.CollectionView.NewItemPlaceholder)
                return;

            var result = MessageBox.Show(
                "Delete this record?\nAll related data will also be removed.",
                "Confirm Delete",
                MessageBoxButton.YesNo,
                MessageBoxImage.Warning);

            if (result != MessageBoxResult.Yes)
                return;

            try
            {
                context.Remove(item);

                await context.SaveChangesAsync();

                // UI обновится автоматически через Local коллекцию
            }
            catch (DbUpdateException)
            {
                MessageBox.Show(
                    "Cannot delete this record.\nIt is used in other data.",
                    "Delete Error",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Unexpected error:\n{ex.Message}",
                    "Error",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }
        }
    }
}