using Development_Demand_Forecasting.Model;
using Development_Demand_Forecasting.Services;
using Google.GenAI;
using Google.GenAI.Types;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.DirectoryServices.ActiveDirectory;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace Development_Demand_Forecasting
{

    public partial class MainWindow : Window
    {
        private readonly Development_Demand_Forecasting.Model.AppContext context;


        public MainWindow()
        {
            InitializeComponent();
            context = new Development_Demand_Forecasting.Model.AppContext();
            context.Database.EnsureCreated();

            productsRadioButton.IsChecked = true;
        }

        private void searchBox_GotFocus(object sender, RoutedEventArgs e)
        {
            placeholderTextBlock.Visibility = Visibility.Collapsed;
        }

        private void searchBox_LostFocus(object sender, RoutedEventArgs e)
        {
            if (string.IsNullOrEmpty(searchBox.Text))
                placeholderTextBlock.Visibility = Visibility.Visible;
        }

        private void Border_MouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        {
            if (e.ChangedButton == MouseButton.Left)
            {
                if (this.WindowState == WindowState.Maximized)
                {
                    double percentHorizontal = e.GetPosition(this).X / this.ActualWidth;
                    double percentVertical = e.GetPosition(this).Y / this.ActualHeight;

                    this.WindowState = WindowState.Normal;

                    this.Left = e.GetPosition(null).X - (this.ActualWidth * percentHorizontal);
                    this.Top = e.GetPosition(null).Y - (this.ActualHeight * percentVertical);
                }

                this.DragMove();
            }
        }

        private void accountsDataGrid_RowEditEnding(object sender, DataGridRowEditEndingEventArgs e)
        {
            if (e.EditAction != DataGridEditAction.Commit)
                return;

            Dispatcher.BeginInvoke(System.Windows.Threading.DispatcherPriority.Background, new Action(async () =>
            {
                try
                {
                    context.ChangeTracker.DetectChanges();
                    if (!context.ChangeTracker.HasChanges())
                    {
                        accountsDataGrid.Items.Refresh();
                        return;
                    }

                    var result = MessageBox.Show(
                        "Save changes?",
                        "Confirm Save",
                        MessageBoxButton.YesNo,
                        MessageBoxImage.Question);

                    if (result != MessageBoxResult.Yes)
                    {
                        context.ChangeTracker.Entries().ToList().ForEach(entry => entry.Reload());
                    }
                    else
                    {
                        await context.SaveChangesAsync();
                    }

                    accountsDataGrid.Items.Refresh();
                }
                catch (Exception ex)
                {
                    MessageBox.Show($"Error saving data:\n{ex.Message}", "Save Error", MessageBoxButton.OK, MessageBoxImage.Error);

                    accountsDataGrid.Items.Refresh();
                }
            }));
        }

        private void accountsDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            var grid = sender as DataGrid;

            var actionColumn = grid.Columns.FirstOrDefault(c => c.Header.ToString() == "Actions");

            if (actionColumn != null)
            {
                actionColumn.DisplayIndex = grid.Columns.Count - 1;
            }
        }

        private void accountsDataGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            if (e.PropertyName == "SupplierId")
            {
                e.Cancel = true;
                return;
            }
            if (e.PropertyName == "ProductId" || e.PropertyName == "WarehouseId")
            {
                e.Cancel = true;
                return;
            }
            if (e.PropertyName == "ProductId")
            {
                e.Cancel = true;
                return;
            }

            var propertyDescriptor = e.PropertyDescriptor as System.ComponentModel.PropertyDescriptor;

            if ((e.PropertyType.IsClass && e.PropertyType != typeof(string)) ||
                typeof(System.Collections.IEnumerable).IsAssignableFrom(e.PropertyType) && e.PropertyType != typeof(string))
            {
                e.Cancel = true;
                return;
            }

            var entityType = context.Model.FindEntityType(propertyDescriptor?.ComponentType);
            if (entityType != null)
            {
                var primaryKey = entityType.FindPrimaryKey();
                if (primaryKey != null && primaryKey.Properties.Any(p => p.Name == e.PropertyName))
                {
                    if (e.PropertyType == typeof(int))
                    {
                        e.Column.Visibility = Visibility.Collapsed;
                    }
                    else
                    {
                        e.Column.IsReadOnly = true;
                    }
                }
            }

            if (e.PropertyType == typeof(DateTime))
            {
                (e.Column as DataGridTextColumn).Binding.StringFormat = "yyyy-MM-dd";
            }
        }

        private void Products_Checked(object sender, RoutedEventArgs e)
        {
            context.Products.Include(p => p.Supplier).Load();
            SetCurrentTable(context.Products.Local.ToObservableCollection());
        }

        private void Suppliers_Checked(object sender, RoutedEventArgs e)
        {
            context.Suppliers.Load();
            SetCurrentTable(context.Suppliers.Local.ToObservableCollection());
        }

        private void Warehouses_Checked(object sender, RoutedEventArgs e)
        {
            context.Warehouses.Load();
            SetCurrentTable(context.Warehouses.Local.ToObservableCollection());
        }

        private void Inventory_Checked(object sender, RoutedEventArgs e)
        {
            context.Inventory.Include(p => p.Warehouse).Load();
            SetCurrentTable(context.Inventory.Local.ToObservableCollection());
        }

        private void Sales_Checked(object sender, RoutedEventArgs e)
        {
            context.SalesHistory.Load();
            SetCurrentTable(context.SalesHistory.Local.ToObservableCollection());
        }

        private void Minus_Click(object sender, RoutedEventArgs e)
        {
            this.WindowState = WindowState.Minimized;
        }

        private void Maximize_Click(object sender, RoutedEventArgs e)
        {
            if (this.WindowState == WindowState.Normal)
            {
                this.WindowState = WindowState.Maximized;
            }
            else
            {
                this.WindowState = WindowState.Normal;
            }
        }

        private void Close_Click(object sender, RoutedEventArgs e)
        {
            Application.Current.Shutdown();
        }

        private bool isPanelOpen = true;

        private void Menu_Click(object sender, RoutedEventArgs e)
        {
            double from = isPanelOpen ? 0 : -SidePanel.ActualWidth;
            double to = isPanelOpen ? -SidePanel.ActualWidth : 0;

            var animation = new DoubleAnimation
            {
                From = from,
                To = to,
                Duration = TimeSpan.FromMilliseconds(300),
                EasingFunction = new QuadraticEase
                {
                    EasingMode = EasingMode.EaseInOut
                }
            };
            SidePanelTransform.BeginAnimation(TranslateTransform.XProperty, animation);

            Storyboard mainBoardStoryboard = isPanelOpen
                ? (Storyboard)FindResource("ExpandMainBoardStoryboard")
                : (Storyboard)FindResource("CollapseMainBoardStoryboard");

            mainBoardStoryboard.Begin();

            isPanelOpen = !isPanelOpen;
        }

        private async void Forcast_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                if (sender is Button btn)
                {
                    if (btn.Content is StackPanel sp)
                    {
                        foreach (var child in sp.Children)
                        {
                            if (child is TextBlock tb)
                            {
                                tb.Text = "In Progress";
                                break;
                            }
                        }
                    }
                }

                var client = new Client(apiKey: "");

                var salesData = context.SalesHistory
                    .ToList();

                var products = context.Products
                    .ToList();

                var inventory = context.Inventory
                    .ToList();

                var productDataList = salesData
                    .GroupBy(s => s.ProductId)
                    .Select(g =>
                    {
                        var productName = products.FirstOrDefault(p => p.ProductId == g.Key)?.Name ?? "Unknown";

                        var monthlySales = g
                            .GroupBy(s => new DateTime(s.Date.Year, s.Date.Month, 1))
                            .Select(mg => mg.Sum(x => x.Quantity))
                            .ToList();

                        var currentStock = inventory.FirstOrDefault(i => i.ProductId == g.Key)?.QuantityOnHand ?? 0;

                        return $"Data for Product {g.Key} ({productName}):\nMonthly sales: [{string.Join(",", monthlySales)}]\nCurrent stock: {currentStock}";
                    })
                    .ToList();

                string dataString = string.Join("\n\n", productDataList);

                string prompt = $@"
            Forecast next month's demand for each product below.
            Return ONLY valid JSON for each product.

            {dataString}

            Output format per product:
              ProductId: number,
              ProductName: text,
              forecast: number,
              recommended_order: number";

                var response = await client.Models.GenerateContentAsync(
                    model: "gemini-3-flash-preview",
                    contents: prompt
                );

                string result = response.Candidates[0].Content.Parts[0].Text;

                MessageBox.Show(result, "Forecast Result", MessageBoxButton.OK, MessageBoxImage.Information);

                if (sender is Button btnReset)
                {
                    if (btnReset.Content is StackPanel spReset)
                    {
                        foreach (var child in spReset.Children)
                        {
                            if (child is TextBlock tb)
                            {
                                tb.Text = "Forcast";
                                break;
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Error: {ex.Message}", "Forecast Error", MessageBoxButton.OK, MessageBoxImage.Error);

                if (sender is Button btnReset)
                {
                    if (btnReset.Content is StackPanel spReset)
                    {
                        foreach (var child in spReset.Children)
                        {
                            if (child is TextBlock tb)
                            {
                                tb.Text = "Forcast";
                                break;
                            }
                        }
                    }
                }
            }
        }
        private async void DeleteRow_Click(object sender, RoutedEventArgs e)
        {
            if (sender is not Button button)
                return;

            var item = button.DataContext;

            var result = MessageBox.Show(
                "Delete this record?\nAll related data will also be removed.",
                "Confirm Delete",
                MessageBoxButton.YesNo,
                MessageBoxImage.Warning);

            if (result != MessageBoxResult.Yes)
                return;

            try
            {
                context.Remove(item);
                await context.SaveChangesAsync();

                var updatedList = currentItems.ToList();
                if (updatedList.Contains(item))
                {
                    updatedList.Remove(item);
                    currentItems = updatedList;
                }
                searchBox_TextChanged(searchBox, null);

                MessageBox.Show("Record deleted successfully.", "Success", MessageBoxButton.OK, MessageBoxImage.Information);
            }
            catch (DbUpdateException)
            {
                context.Entry(item).Reload();

                MessageBox.Show(
                    "Cannot delete this record.\nIt is used in other data.",
                    "Delete Error",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Unexpected error:\n{ex.Message}",
                    "Error",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }
        }

        private IEnumerable<object> currentItems;
        private System.Reflection.PropertyInfo[] currentProperties;

        private void SetCurrentTable<T>(ObservableCollection<T> items)
        {
            if (items == null)
            {
                currentItems = new List<object>();
                currentProperties = Array.Empty<System.Reflection.PropertyInfo>();
                accountsDataGrid.ItemsSource = currentItems;
                return;
            }

            currentItems = items.Cast<object>().ToList();
            currentProperties = typeof(T).GetProperties()
                .Where(p => !p.PropertyType.IsClass || p.PropertyType == typeof(string))
                .ToArray();

            accountsDataGrid.ItemsSource = currentItems;
        }

        private void searchBox_TextChanged(object sender, TextChangedEventArgs e)
        {
            if (currentItems == null || currentProperties == null)
                return;

            string filter = searchBox.Text.ToLower();

            if (string.IsNullOrWhiteSpace(filter))
            {
                accountsDataGrid.ItemsSource = currentItems;
                return;
            }

            var filtered = currentItems
                .Where(item => currentProperties.Any(p =>
                {
                    var value = p.GetValue(item);
                    if (value == null) return false;

                    if (value is DateTime dt)
                        return dt.ToString("yyyy-MM-dd").Contains(filter);

                    return value.ToString().ToLower().Contains(filter);
                }))
                .ToList();

            accountsDataGrid.ItemsSource = filtered;
        }

        private void RadioButton_Checked_1(object sender, RoutedEventArgs e)
        {
            Forecast forcastWindow = new Forecast();
            forcastWindow.Show();
            this.Close();
        }

        private void export_Click(object sender, RoutedEventArgs e)
        {
            var itemsToExport = accountsDataGrid.ItemsSource?.Cast<object>();

            if (itemsToExport == null || !itemsToExport.Any())
            {
                MessageBox.Show("There is no data to export in the current table.", "Export", MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }

            var firstItemType = itemsToExport.First().GetType();
            string defaultFileName = $"{firstItemType.Name}_Export.xlsx";

            ExcelExportService.ExportData(itemsToExport, defaultFileName);
        }

        private void Add_Click(object sender, RoutedEventArgs e)
        {
            bool? result = false;

            if (productsRadioButton.IsChecked == true)
            {
                AddItem addProductWindow = new AddItem("Product");
                result = addProductWindow.ShowDialog();
                if (result == true) Products_Checked(null, null);
            }
            else if (suppliersRadioButton.IsChecked == true)
            {
                AddItem addSupplierWindow = new AddItem("Supplier");
                result = addSupplierWindow.ShowDialog();
                if (result == true) Suppliers_Checked(null, null);
            }
            else if (warehousesRadioButton.IsChecked == true)
            {
                AddItem addWarehouseWindow = new AddItem("Warehouse");
                result = addWarehouseWindow.ShowDialog();
                if (result == true) Warehouses_Checked(null, null);
            }
            else if (inventoryRadioButton.IsChecked == true)
            {
                AddItem addInventoryWindow = new AddItem("Inventory");
                result = addInventoryWindow.ShowDialog();
                if (result == true) Inventory_Checked(null, null);
            }
            else if (salesRadioButton.IsChecked == true)
            {
                AddItem addSalesWindow = new AddItem("SalesHistory");
                result = addSalesWindow.ShowDialog();
                if (result == true) Sales_Checked(null, null);
            }
        }
    }
}